import type { Product, Review } from "./types";

export const demoProducts: Product[] = [
  {
    id: "demo-studs-velocity",
    slug: "velocity-fg-cobalt",
    name: "Velocity FG Cobalt",
    category: "studs",
    description: "A close-to-ball knit upper with a stable molded plate for firm natural ground.",
    price: 128,
    compareAtPrice: 148,
    images: ["/images/category-studs.png", "/images/hero-boot.png"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    stock: 18,
    featured: true,
    badge: "New drop",
    active: true,
    createdAt: "2026-07-24T10:00:00.000Z",
  },
  {
    id: "demo-studs-control",
    slug: "control-fg-night",
    name: "Control FG Night",
    category: "studs",
    description: "Textured touch zones and a low-profile collar built for fast changes of direction.",
    price: 116,
    images: ["/images/hero-boot.png", "/images/category-studs.png"],
    sizes: ["6", "7", "8", "9", "10"],
    stock: 11,
    featured: true,
    badge: "Staff pick",
    active: true,
    createdAt: "2026-07-20T10:00:00.000Z",
  },
  {
    id: "demo-grippers-lock",
    slug: "lock-in-grip-sleeves",
    name: "Lock-In Grip Sleeves",
    category: "grippers",
    description: "Technical compression sleeves with mapped silicone traction for less movement inside the boot.",
    price: 24,
    images: ["/images/category-grippers.png"],
    sizes: ["S/M", "L/XL"],
    stock: 34,
    featured: true,
    badge: "Training essential",
    active: true,
    createdAt: "2026-07-18T10:00:00.000Z",
  },
  {
    id: "demo-grippers-ankle",
    slug: "pivot-ankle-grippers",
    name: "Pivot Ankle Grippers",
    category: "grippers",
    description: "Low-profile ankle grippers with breathable knit and targeted traction panels.",
    price: 18,
    images: ["/images/category-grippers.png"],
    sizes: ["S/M", "L/XL"],
    stock: 27,
    featured: false,
    active: true,
    createdAt: "2026-07-14T10:00:00.000Z",
  },
  {
    id: "demo-socks-match",
    slug: "matchday-pro-socks",
    name: "Matchday Pro Socks",
    category: "socks",
    description: "Knee-high ribbed match socks with cushioned impact zones and a locked-in arch.",
    price: 20,
    images: ["/images/category-socks.png"],
    sizes: ["S", "M", "L"],
    stock: 41,
    featured: true,
    badge: "2 colours",
    active: true,
    createdAt: "2026-07-16T10:00:00.000Z",
  },
  {
    id: "demo-socks-training",
    slug: "training-cut-socks",
    name: "Training Cut Socks",
    category: "socks",
    description: "Cushioned crew socks made to pair cleanly with sleeves and ankle grippers.",
    price: 14,
    images: ["/images/category-socks.png"],
    sizes: ["S", "M", "L"],
    stock: 52,
    featured: false,
    active: true,
    createdAt: "2026-07-10T10:00:00.000Z",
  },
  {
    id: "demo-ball-match",
    slug: "crossline-match-ball",
    name: "Crossline Match Ball",
    category: "footballs",
    description: "A thermally bonded match ball with a textured casing for a clean, predictable flight.",
    price: 46,
    images: ["/images/category-footballs.png"],
    sizes: ["5"],
    stock: 22,
    featured: true,
    badge: "Match ready",
    active: true,
    createdAt: "2026-07-22T10:00:00.000Z",
  },
  {
    id: "demo-ball-training",
    slug: "crossline-training-ball",
    name: "Crossline Training Ball",
    category: "footballs",
    description: "A durable machine-stitched ball built for repeated training sessions on mixed surfaces.",
    price: 30,
    images: ["/images/category-footballs.png"],
    sizes: ["4", "5"],
    stock: 38,
    featured: false,
    active: true,
    createdAt: "2026-07-08T10:00:00.000Z",
  },
];

export const demoReviews: Review[] = [
  {
    id: "review-a",
    productId: "demo-studs-velocity",
    productName: "Velocity FG Cobalt",
    author: "Yusuf Rahman",
    rating: 5,
    title: "Secure from the first session",
    body: "The upper settled quickly and the plate felt stable when changing direction. The size guide was accurate for me.",
    status: "approved",
    createdAt: "2026-07-27T15:30:00.000Z",
  },
  {
    id: "review-b",
    productId: "demo-grippers-lock",
    productName: "Lock-In Grip Sleeves",
    author: "Haris Mahmood",
    rating: 4,
    title: "Useful on hard training days",
    body: "They stay in place and reduce the sliding I usually get late in a session. The fabric also dries quickly.",
    status: "approved",
    createdAt: "2026-07-25T11:10:00.000Z",
  },
  {
    id: "review-c",
    productId: "demo-ball-match",
    productName: "Crossline Match Ball",
    author: "Adeel Khan",
    email: "adeel@example.com",
    rating: 5,
    title: "Pending demo review",
    body: "The surface has a good amount of grip in damp conditions and the flight stays consistent.",
    status: "pending",
    createdAt: "2026-07-30T08:20:00.000Z",
  },
];
